FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /app

COPY pom.xml .

COPY mvnw .

COPY .mvn ./.mvn

RUN chmod +x ./mvnw

COPY src ./src

RUN --mount=type=cache,target=/root/.m2 ./mvnw package -DskipTests

FROM eclipse-temurin:17-jre-alpine

ENV PORT=8080
EXPOSE 8080

ARG JAR_FILE=/app/target/*.jar

COPY --from=builder ${JAR_FILE} app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
